matrix:
  include:
  - language: python
    name: Compatibility Test (Python 3.6 + Bandit)
    python: 3.6
    before_install:
    - git clone https://github.com/TravisToolbox/bandit.git
    install:
    - "./bandit/install.sh"
    script:
    - "./bandit/scan.sh"
  - language: python
    name: Compatibility Test (Python 3.6 + Pur)
    python: 3.6
    before_install:
    - git clone https://github.com/TravisToolbox/pur.git
    install:
    - "./pur/install.sh"
    script:
    - "./pur/scan.sh"
  - language: python
    name: Compatibility Test (Python 3.6 + Pycodestyle)
    python: 3.6
    before_install:
    - git clone https://github.com/TravisToolbox/pycodestyle.git
    install:
    - "./pycodestyle/install.sh"
    script:
    - "./pycodestyle/scan.sh"
  - language: python
    name: Compatibility Test (Python 3.7 + Bandit)
    python: 3.7
    before_install:
    - git clone https://github.com/TravisToolbox/bandit.git
    install:
    - "./bandit/install.sh"
    script:
    - "./bandit/scan.sh"
  - language: python
    name: Compatibility Test (Python 3.7 + Pur)
    python: 3.7
    before_install:
    - git clone https://github.com/TravisToolbox/pur.git
    install:
    - "./pur/install.sh"
    script:
    - "./pur/scan.sh"
  - language: python
    name: Compatibility Test (Python 3.7 + Pycodestyle)
    python: 3.7
    before_install:
    - git clone https://github.com/TravisToolbox/pycodestyle.git
    install:
    - "./pycodestyle/install.sh"
    script:
    - "./pycodestyle/scan.sh"
  - language: python
    name: Compatibility Test (Python 3.8 + Bandit)
    python: 3.8
    before_install:
    - git clone https://github.com/TravisToolbox/bandit.git
    install:
    - "./bandit/install.sh"
    script:
    - "./bandit/scan.sh"
  - language: python
    name: Compatibility Test (Python 3.8 + Pur)
    python: 3.8
    before_install:
    - git clone https://github.com/TravisToolbox/pur.git
    install:
    - "./pur/install.sh"
    script:
    - "./pur/scan.sh"
  - language: python
    name: Compatibility Test (Python 3.8 + Pycodestyle)
    python: 3.8
    before_install:
    - git clone https://github.com/TravisToolbox/pycodestyle.git
    install:
    - "./pycodestyle/install.sh"
    script:
    - "./pycodestyle/scan.sh"
  - language: python
    name: Compatibility Test (Python 3.9 + Bandit)
    python: 3.9
    before_install:
    - git clone https://github.com/TravisToolbox/bandit.git
    install:
    - "./bandit/install.sh"
    script:
    - "./bandit/scan.sh"
  - language: python
    name: Compatibility Test (Python 3.9 + Pur)
    python: 3.9
    before_install:
    - git clone https://github.com/TravisToolbox/pur.git
    install:
    - "./pur/install.sh"
    script:
    - "./pur/scan.sh"
  - language: python
    name: Compatibility Test (Python 3.9 + Pycodestyle)
    python: 3.9
    before_install:
    - git clone https://github.com/TravisToolbox/pycodestyle.git
    install:
    - "./pycodestyle/install.sh"
    script:
    - "./pycodestyle/scan.sh"
  - language: ruby
    name: YAML Linting (rvm 3.0)
    rvm: 3.0
    before_install:
    - git clone https://github.com/TravisToolbox/yaml-lint
    install:
    - "./yaml-lint/install.sh"
    script:
    - "./yaml-lint/scan.sh"
  - language: bash
    name: Shellcheck (Bash)
    os: linux
    arch: arm64-graviton2
    before_install:
    - git clone https://github.com/TravisToolbox/shellcheck
    install:
    - "./shellcheck/install.sh"
    script:
    - "./shellcheck/scan.sh"
  - language: ruby
    name: Link Checking (rvm 3.0)
    rvm: 3.0
    env:
    - WHITELIST="https://img.shields.io"
    - EXCLUDE_FILES="CHANGELOG.md"
    before_install:
    - git clone https://github.com/TravisToolbox/awesomebot
    install:
    - "./awesomebot/install.sh"
    script:
    - "./awesomebot/scan.sh"
notifications:
  email: false
  slack:
    secure: YxYXjMCVwcoMUYrAyPwbd4FFM9F3oW0ufIqlmbZK72a/forTcqdw8+aumoRsRBuZ+6m1fLUcDcvQ1VarD2lBv6589CFFllk3nl0XzW1mM8EMIoza8ZEtZBVbElsdmO9kkWYGM3q6GBWUyxYA6eD5D+n2CpLMjcgeLWCsOGDn1AWok/ZNgUM7YFRYXJVpOWJsJKItzTuBGUnl0tEbI/BZnZJQJeTUXed5GbBSIr5mw50Jkx/A7UnCBt7QyZzyY18qwrV7lMR9QqgO+JkTk4wtTjC/mHj3aB+u181PacVUf4t1fMXc1BcxcrHkhrDKWEWT5nB1WItH6ZuI8ayuuMmug3XXdV5SdM7YcxrwpVw2RwGcXrawCkBwPrQbdRI0sAeutIOg6OZEfnBXmTBNa0D2UiGW9zZJXdghAlLcwH/R+ZC5wvQ541NrRG6NzMGhng5TEfiBrsMj0yCUU2oJGOfUTEjc0uiwjxhRb0xMDnX4G0zsHz0OqIMXoGbehRu9aq4NcthFCLdkr/TZPEqm3YB8Ln5n8GneVJAOYh/WBeZfFSFGQAJ3CnbfTqunAd3gz44jentfDxQSseeRZ35FCOIQ+4qIQvuOaYiA3hHFF3sxJF7JIsF2/56XWu8opTdW263HikndUKbDRoeoUb32t3OByyp84FYqhSCsrDp35clz5BM=
